version: '3.4'

services:
  users:
    image: ${DOCKER_REGISTRY-}users
    build:
      context: .
      dockerfile: Users/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5002:80"
      - "5003:443"
    depends_on:
      - db

  orders:
    image: ${DOCKER_REGISTRY-}orders
    build:
      context: .
      dockerfile: Orders/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5004:80"
      - "5005:443"
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1456:1456"
 
    environment:
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"

  webapp:
    image: ${DOCKER_REGISTRY-}webapp:v1
    build:
      context: ./SPA
      dockerfile: Dockerfile
    ports:
        - 3000:80